### ISSUE TITLE
update api-schemas

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/cold-war-boardgame#91]
- [x] list of top/bottom cards  for decks where is revealed for player
- [x] status of game - is_active: bool #97 
- [x] game/preset/faction merge with game/preset priority with query and use different option for priority (my, you, rand)
- [x] game/next with query turn,phase as bool

**Comment by KonstantinKlepikov** [comment]
faction = cia, kgb
priority = true, false, random

**Comment by KonstantinKlepikov** [comment]
@chemeshuggah changes:

1. now game decks contains only `pile` (this not list of Card objects, this is list of cards names) and `deck_len`. `pile_len` field is removed
2. added `PlayerGroupOrObjectivreCard` schema. Here is:
    ```yml
            "example": {
                "is_in_deck": True,
                "is_in_play": False,
                "is_active": True,
                "position": 0,
                "name": "Master Spy",
                }
    ```
  
    `is_active` mark - can player use group or objective card. Position mark position of card in deck, if it known by player
3. added field `mission_card` to game cards schema - in this field we observe mission objective card, defined in any turn
